//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kabmlg
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowing_record_status
    {
        public int id { get; set; }
        public int borrowing_record_id { get; set; }
        public string from_status { get; set; }
        public string to_status { get; set; }
        public string notes { get; set; }
        public int user_id { get; set; }
        public byte[] created_at { get; set; }
    
        public virtual borrowing_record borrowing_record { get; set; }
        public virtual users users { get; set; }
    }
}
