//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kabmlg
{
    using System;
    using System.Collections.Generic;
    
    public partial class devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public devices()
        {
            this.borrowing_record = new HashSet<borrowing_record>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
        public string status { get; set; }
        public string code { get; set; }
        public byte[] created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowing_record> borrowing_record { get; set; }
    }
}
